### ISSUE TITLE
Extra tissues to match with GTex

### ISSUE THREAD

**Issue by jergosh** [jespermaag/gganatogram#15]
Hi, 
We would very much like to use gganatograms for a couple of projects running in our group. I think it fits very well with what we would like to demonstrate using GTex data, except that the pituitary and salivary glands are missing in gganatogram. Would it be possible to add them as two (optional) tissues? I think matching between gganatogram and GTex tissues would potentially be useful to other people using these data.

Best,
Greg

**Comment by jespermaag** [comment]
Hi Greg,
I'll see if I can add them this week.
I'll keep you posted.

**Comment by jergosh** [comment]
That's great! Thanks very much, appreciate it.

**Comment by jespermaag** [comment]
Fixed it now for human.

```
hgMale_key[hgMale_key$type=='hormone',]
                 organ    type colour      value
1        thyroid_gland hormone yellow  0.9906961
5      pituitary_gland hormone yellow 13.0039467
38      salivary_gland hormone yellow  9.6428882
39       parotid_gland hormone yellow 18.9632077
40 submandibular_gland hormone yellow  3.7169400
45       adrenal_gland hormone yellow 19.1863695
```

```
 hgFemale_key[hgFemale_key$type=='hormone',]
                 organ colour    type      value
16     pituitary_gland yellow hormone  0.4179739
43       thyroid_gland yellow hormone 13.7657837
45       parotid_gland yellow hormone 19.4480276
50       adrenal_gland yellow hormone 11.3729465
55      salivary_gland yellow hormone  8.5902632
69 submandibular_gland yellow hormone 15.0929987
```
