### ISSUE TITLE
YEAST PLOT

### ISSUE THREAD

**Issue by kobachii-d** [jespermaag/gganatogram#16]
This is not really an issue but ... is it possible to create a plot of Saccharomyces cerevisiae using gganatogram? This yeast species exists in the repository https://www.ebi.ac.uk/gxa/home but I am not sure how to specify that in the command line.

Thanks
Kobchai

**Comment by jespermaag** [comment]
Hi Kobchai,

Unfortunately, there's no Saccharomyces cerevisia anatogram https://ebi-gene-expression-group.github.io/anatomogram/

If you know of a well annotated open source SVG file, or want to draw one yourself, I would be interested in adding it.

Cheers,
Jesper

**Comment by kobachii-d** [comment]
Alright thanks. I might look around for the svg of this organism. 

Kobchai

**Comment by jespermaag** [comment]
Great, let me know if you find, or create, something!
