### ISSUE TITLE
Feature request: Brain anatomy

### ISSUE THREAD

**Issue by AMChalkie** [jespermaag/gganatogram#23]
Hi,

Would really appreciate the ability to map onto specific regions of the brain.

Thanks again for a great piece of software.

/Alistair

**Comment by brennanpincardiff** [comment]
Hi Alistair, 
    You might like to check out ggseg which is focussed on brain regions
     (https://lcbc-uio.github.io/ggseg/)
     (https://github.com/LCBC-UiO/ggseg)
Best wishes, 
Paul

**Comment by AMChalkie** [comment]
Thanks @brennanpincardiff for the tip, that looks like just what we will need.

**Comment by ajmoralesa** [comment]
@brennanpincardiff are you aware of anything similar to `ggseg` that could be used for human skeletal muscles?
