### ISSUE TITLE
Share your workflow to create the data necessary for the images...

### ISSUE THREAD

**Issue by brennanpincardiff** [jespermaag/gganatogram#3]
Hi Jesper, 
     Would it be possible for you to share the workflow that moved the anatogram images from the figure in ArrayExpress Expression Atlas to this package, please?
     If so, I think I (and others) might be able to help to make this package useful. As discussed on twitter, it would be great to add the images for female and other species too. 
    Thanks, 
Paul

**Comment by jespermaag** [comment]
Hi Paul,
Thanks for your interest!

I've added the workflow and svg's to generate the necessary coordinate files.
It's a bit of a Hodge podge..

**Comment by jespermaag** [comment]
I'm struggling to retrieve all data from the SVGs, so I miss a few tissues.
