### ISSUE TITLE
Fix reference to Expression Atlas

### ISSUE THREAD

**Issue by alfonsomunozpomer** [jespermaag/gganatogram#4]
Hi, I just wanted to let you know that [ArrayExpress](https://www.ebi.ac.uk/arrayexpress) and [Expression Atlas](https://www.ebi.ac.uk/gxa) are two different services. Could you fix the text at your earliest convenience in the README file?

Many thanks in advance!

**Comment by jespermaag** [comment]
Removed references to ArrayExpressed, and added better referencing to Expression Atlas
