### ISSUE TITLE
hgFemale_key doesn't have spinal cord?

### ISSUE THREAD

**Issue by chienc1** [jespermaag/gganatogram#7]
Hi All, 

 This is an awesome tool and I really like it! I was wondering though, if perhaps you could add in the spinal cord for the hgFemale_key so that it can be displayed?

Thanks so much!

Best wishes, 
Claudia

**Comment by jespermaag** [comment]
Thanks Claudia!

I'm not sure why it was missing. I'll add it ASAP.

**Comment by chienc1** [comment]
Thanks Jesper! :)
